Title: GenExAT App - Shiny App
Description: "The GenExAT App: R Shiny Transcriptome Analysis Resource Tool"
Google_analytics: 
show_downloads: true
Theme: jekyll-theme-dinky
Gems:
  - jekyll-mentions
